# Generated by Django 3.2.9 on 2021-12-07 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proffy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullName', models.CharField(max_length=250)),
                ('whatsapp', models.CharField(max_length=250)),
                ('email', models.CharField(blank=True, max_length=250)),
                ('estado', models.CharField(blank=True, max_length=250)),
                ('cidade', models.CharField(blank=True, max_length=250)),
                ('bio', models.TextField()),
                ('time_from', models.CharField(blank=True, max_length=250)),
                ('cost', models.IntegerField(verbose_name='R$ ')),
                ('subject', models.CharField(max_length=250)),
                ('weekday', models.CharField(max_length=250)),
                ('avatar', models.URLField(max_length=250, verbose_name='url')),
                ('show', models.BooleanField(default=False, verbose_name='Ocultar Proffy')),
            ],
        ),
    ]
